/**
 * Document Rules Engine
 * Defines all visa checklist categories, required/optional flags,
 * and conditional requirements based on applicant data.
 */

export const DOCUMENT_RULES = {
  visaD: {
    key: "visaD",
    label: "VISA-D Form",
    section: "Application Forms & Basic Documents",
    sectionOrder: 1,
    order: 1,
    required: true,
    multiple: false,
  },
  coverLetter: {
    key: "coverLetter",
    label: "Cover Letter / Visa Application Letter",
    section: "Application Forms & Basic Documents",
    sectionOrder: 1,
    order: 2,
    required: true,
    multiple: false,
  },
  currentPassport: {
    key: "currentPassport",
    label: "Current Passport Information Page",
    section: "Application Forms & Basic Documents",
    sectionOrder: 1,
    order: 3,
    required: true,
    multiple: false,
  },
  selfPhotos: {
    key: "selfPhotos",
    label: "Self Photos (4.0 × 3.5 cm, white background)",
    section: "Application Forms & Basic Documents",
    sectionOrder: 1,
    order: 4,
    required: true,
    multiple: true,
  },
  previousPassport: {
    key: "previousPassport",
    label: "Previous Passport Information Page",
    section: "Application Forms & Basic Documents",
    sectionOrder: 1,
    order: 5,
    required: false,
    multiple: false,
  },
  ssc: {
    key: "ssc",
    label: "SSC Certificate & Transcript",
    section: "Academic Documents",
    sectionOrder: 2,
    order: 6,
    required: true,
    multiple: true,
  },
  hsc: {
    key: "hsc",
    label: "HSC Certificate & Transcript",
    section: "Academic Documents",
    sectionOrder: 2,
    order: 7,
    required: true,
    multiple: true,
  },
  bachelor: {
    key: "bachelor",
    label: "Bachelor / Honours Certificate & Transcript",
    section: "Academic Documents",
    sectionOrder: 2,
    order: 8,
    required: false,
    requiredWhen: (a) => a.applicationLevel === "masters",
    multiple: true,
  },
  masters: {
    key: "masters",
    label: "Master's Certificate & Transcript",
    section: "Academic Documents",
    sectionOrder: 2,
    order: 9,
    required: false,
    multiple: true,
  },
  offerLetter: {
    key: "offerLetter",
    label: "Offer Letter / Admission Letter",
    section: "University Documents",
    sectionOrder: 3,
    order: 10,
    required: true,
    multiple: false,
  },
  preEnrollment: {
    key: "preEnrollment",
    label: "Pre-enrollment Letter",
    section: "University Documents",
    sectionOrder: 3,
    order: 11,
    required: false,
    multiple: false,
  },
  cv: {
    key: "cv",
    label: "Curriculum Vitae",
    section: "Academic & Profile Documents",
    sectionOrder: 4,
    order: 12,
    required: true,
    multiple: false,
  },
  languageCert: {
    key: "languageCert",
    label: "Language Proficiency Certificate",
    section: "Academic & Profile Documents",
    sectionOrder: 4,
    order: 13,
    required: true,
    multiple: true,
  },
  recommendation: {
    key: "recommendation",
    label: "Recommendation Letter(s)",
    section: "Academic & Profile Documents",
    sectionOrder: 4,
    order: 14,
    required: false,
    multiple: true,
  },
  extracurricular: {
    key: "extracurricular",
    label: "Extracurricular Certificates",
    section: "Academic & Profile Documents",
    sectionOrder: 4,
    order: 15,
    required: false,
    multiple: true,
  },
  cimeaComparability: {
    key: "cimeaComparability",
    label: "CIMEA Statement of Comparability",
    section: "Credential Verification",
    sectionOrder: 5,
    order: 16,
    required: true,
    multiple: false,
  },
  cimeaVerification: {
    key: "cimeaVerification",
    label: "CIMEA Statement of Verification",
    section: "Credential Verification",
    sectionOrder: 5,
    order: 17,
    required: true,
    multiple: false,
  },
  applicantBankStatement: {
    key: "applicantBankStatement",
    label: "Applicant Bank Statement",
    section: "Applicant Financial Documents",
    sectionOrder: 6,
    order: 18,
    required: true,
    multiple: true,
  },
  applicantBankSolvency: {
    key: "applicantBankSolvency",
    label: "Applicant Bank Solvency Certificate",
    section: "Applicant Financial Documents",
    sectionOrder: 6,
    order: 19,
    required: true,
    multiple: false,
  },
  sponsorBankStatement: {
    key: "sponsorBankStatement",
    label: "Sponsor Bank Statement",
    section: "Sponsor Financial Documents",
    sectionOrder: 7,
    order: 20,
    required: true,
    requiredWhen: (a) => a.sponsorshipType !== "self",
    multiple: true,
    notRequiredMessage: "Not required for self-sponsored applicant",
  },
  sponsorBankSolvency: {
    key: "sponsorBankSolvency",
    label: "Sponsor Bank Solvency Certificate",
    section: "Sponsor Financial Documents",
    sectionOrder: 7,
    order: 21,
    required: true,
    requiredWhen: (a) => a.sponsorshipType !== "self",
    multiple: false,
    notRequiredMessage: "Not required for self-sponsored applicant",
  },
  financialDeclaration: {
    key: "financialDeclaration",
    label: "Financial Declaration Letter",
    section: "Sponsor Financial Documents",
    sectionOrder: 7,
    order: 22,
    required: true,
    requiredWhen: (a) => a.sponsorshipType !== "self",
    multiple: false,
    notRequiredMessage: "Not required for self-sponsored applicant",
  },
  jobSalary: {
    key: "jobSalary",
    label: "Job Documents / Salary Proof",
    section: "Income Proof",
    sectionOrder: 8,
    order: 23,
    required: false,
    multiple: true,
  },
  tradeLicense: {
    key: "tradeLicense",
    label: "Trade License",
    section: "Income Proof",
    sectionOrder: 8,
    order: 24,
    required: false,
    multiple: true,
  },
  rentalIncome: {
    key: "rentalIncome",
    label: "Rental Income Proof",
    section: "Income Proof",
    sectionOrder: 8,
    order: 25,
    required: false,
    multiple: true,
  },
  dps: {
    key: "dps",
    label: "DPS",
    section: "Income Proof",
    sectionOrder: 8,
    order: 26,
    required: false,
    multiple: true,
  },
  fdr: {
    key: "fdr",
    label: "FDR",
    section: "Income Proof",
    sectionOrder: 8,
    order: 27,
    required: false,
    multiple: true,
  },
  otherIncome: {
    key: "otherIncome",
    label: "Other Income Documents",
    section: "Income Proof",
    sectionOrder: 8,
    order: 28,
    required: false,
    multiple: true,
  },
  jobExperience: {
    key: "jobExperience",
    label: "Job Experience Letter",
    section: "Employment Documents",
    sectionOrder: 9,
    order: 29,
    required: false,
    multiple: true,
  },
  noc: {
    key: "noc",
    label: "NOC",
    section: "Employment Documents",
    sectionOrder: 9,
    order: 30,
    required: false,
    multiple: false,
  },
  employeeId: {
    key: "employeeId",
    label: "Employee ID Card / Supporting Letter",
    section: "Employment Documents",
    sectionOrder: 9,
    order: 31,
    required: false,
    multiple: true,
  },
  tin: {
    key: "tin",
    label: "TIN Certificate",
    section: "Tax Documents",
    sectionOrder: 10,
    order: 32,
    required: false,
    multiple: false,
  },
  taxReturn: {
    key: "taxReturn",
    label: "Tax Return Certificate",
    section: "Tax Documents",
    sectionOrder: 10,
    order: 33,
    required: false,
    multiple: true,
  },
  familyCertificate: {
    key: "familyCertificate",
    label: "Family Certificate",
    section: "Family & Personal Documents",
    sectionOrder: 11,
    order: 34,
    required: true,
    multiple: false,
  },
  fatherNid: {
    key: "fatherNid",
    label: "Father NID",
    section: "Family & Personal Documents",
    sectionOrder: 11,
    order: 35,
    required: true,
    multiple: false,
  },
  motherNid: {
    key: "motherNid",
    label: "Mother NID",
    section: "Family & Personal Documents",
    sectionOrder: 11,
    order: 36,
    required: true,
    multiple: false,
  },
  birthCertificate: {
    key: "birthCertificate",
    label: "Applicant Birth Certificate",
    section: "Family & Personal Documents",
    sectionOrder: 11,
    order: 37,
    required: true,
    multiple: false,
  },
  applicantNid: {
    key: "applicantNid",
    label: "Applicant NID",
    section: "Family & Personal Documents",
    sectionOrder: 11,
    order: 38,
    required: true,
    multiple: false,
  },
  accommodation: {
    key: "accommodation",
    label: "Accommodation Proof",
    section: "Travel & Stay",
    sectionOrder: 12,
    order: 39,
    required: true,
    multiple: true,
  },
  airTicket: {
    key: "airTicket",
    label: "Air Ticket Booking",
    section: "Travel & Stay",
    sectionOrder: 12,
    order: 40,
    required: false,
    multiple: true,
  },
  travelInsurance: {
    key: "travelInsurance",
    label: "Health & Travel Insurance",
    section: "Travel & Stay",
    sectionOrder: 12,
    order: 41,
    required: true,
    multiple: true,
  },
  marriageCertificate: {
    key: "marriageCertificate",
    label: "Marriage Certificate / Nikah Nama",
    section: "Civil Status",
    sectionOrder: 13,
    order: 42,
    required: false,
    requiredWhen: (a) => a.civilStatus === "married",
    multiple: false,
  },
  divorceCertificate: {
    key: "divorceCertificate",
    label: "Divorce Certificate / Talaq Nama",
    section: "Civil Status",
    sectionOrder: 13,
    order: 43,
    required: false,
    requiredWhen: (a) => a.civilStatus === "divorced",
    multiple: false,
  },
  deathCertificate: {
    key: "deathCertificate",
    label: "Death Certificate of Spouse",
    section: "Civil Status",
    sectionOrder: 13,
    order: 44,
    required: false,
    requiredWhen: (a) => a.civilStatus === "widowed",
    multiple: false,
  },
  parentConsent: {
    key: "parentConsent",
    label: "Parent Consent",
    section: "Minor Applicants",
    sectionOrder: 14,
    order: 45,
    required: false,
    requiredWhen: (a) => a.isMinor === true,
    multiple: true,
  },
  parentPassports: {
    key: "parentPassports",
    label: "Parent Passports",
    section: "Minor Applicants",
    sectionOrder: 14,
    order: 46,
    required: false,
    requiredWhen: (a) => a.isMinor === true,
    multiple: true,
  },
  parentFinancial: {
    key: "parentFinancial",
    label: "Parent Financial Documents",
    section: "Minor Applicants",
    sectionOrder: 14,
    order: 47,
    required: false,
    requiredWhen: (a) => a.isMinor === true,
    multiple: true,
  },
  guardianProof: {
    key: "guardianProof",
    label: "Guardian / Custodian Proof",
    section: "Minor Applicants",
    sectionOrder: 14,
    order: 48,
    required: false,
    requiredWhen: (a) => a.isMinor === true,
    multiple: true,
  },
  residencePermit: {
    key: "residencePermit",
    label: "Bangladesh Residence Permit",
    section: "Non-Bangladeshi Applicants",
    sectionOrder: 15,
    order: 49,
    required: false,
    requiredWhen: (a) => a.nationality && a.nationality.toLowerCase() !== "bangladeshi" && a.nationality.toLowerCase() !== "bangladesh",
    multiple: false,
  },
  otherSupporting: {
    key: "otherSupporting",
    label: "Other Supporting Documents",
    section: "Additional Documents",
    sectionOrder: 16,
    order: 50,
    required: false,
    multiple: true,
  },
};

export function getOrderedRules() {
  return Object.values(DOCUMENT_RULES).sort((a, b) => a.order - b.order);
}

export function isDocumentRequired(rule, applicant) {
  if (typeof rule.requiredWhen === "function") {
    return rule.requiredWhen(applicant);
  }
  return !!rule.required;
}

export function getApplicableRules(applicant) {
  return getOrderedRules().filter((rule) => {
    if (typeof rule.requiredWhen === "function") {
      const conditionTrue = rule.requiredWhen(applicant);
      if (["marriageCertificate", "divorceCertificate", "deathCertificate",
           "parentConsent", "parentPassports", "parentFinancial", "guardianProof",
           "residencePermit"].includes(rule.key)) {
        return conditionTrue;
      }
      return true;
    }
    return true;
  });
}

export function getRulesBySection(applicant) {
  const applicable = getApplicableRules(applicant);
  const sections = {};
  for (const rule of applicable) {
    if (!sections[rule.section]) {
      sections[rule.section] = {
        name: rule.section,
        order: rule.sectionOrder,
        rules: [],
      };
    }
    sections[rule.section].rules.push(rule);
  }
  return Object.values(sections).sort((a, b) => a.order - b.order);
}
